# Define UI
shinyUI(fluidPage(
    
    tags$style( 
        str_c(zoom_reverse, #Reverse zoom for plotly graphs to avoid glitches and make hover work
              zoom_css, # Adjust zoom to fit 1 year without horizontal scrolling
              error_position_css,
              form_group_css) #Manually adjust position of validation messages
        
    ),
    
    
    # Application title
    titlePanel(tagList(
      h1("Buckets Dashboard", style = "display: inline"),
      actionButton("reload_app", "Reload .buckets file", style = "position: absolute; right: 18px;")
      ),
      windowTitle = "Buckets Dashboard"),

    # Sidebar with input controls / filters
    sidebarLayout(
        sidebarPanel(width = 2,
            # Input of date range for filtering
            airDatepickerInput("date_range",
                               "Select months for the reports",
                               autoClose = TRUE,
                               update_on = "change",
                               separator = " to ",
                               toggleSelected = FALSE,
                               addon = "none",
                               dateFormat = "yyyy-M",
                               range = TRUE,
                               view = "months",
                               minView = "months",
                               todayButton = FALSE,
                               value = c(date_from, date_to),
                               minDate = min(monthly$month),
                               maxDate = max(monthly$month)),
            actionButton(inputId = "select_all_dates", 
                         label = "All Months",
                         style="margin-bottom: 5px;"),
            actionButton(inputId = "select_current_month", 
                         label = "Current Month",
                         style="margin-bottom: 5px;"),
            br(),
            actionButton(inputId = "select_current_year", 
                         label = "Current Year",
                         style="margin-bottom: 5px;"),
            # Input controls for filtering Buckets
            p(strong("Select buckets for the reports"),
              style="margin-bottom: 5px;"),
            actionButton(inputId = "select_all_buckets", 
                         label = "Show All Buckets",
                         style="margin-bottom: 5px;"),
        pickerInput(inputId = "income_buckets_filter_choices",
                    label = NULL,
                    selected = unlist(income_named_list, use.names = FALSE),
                    choices = income_named_list,
                    multiple = TRUE,
                    width = "fit",
                    options = list(`actions-box` = TRUE,
                                   header = "Income Buckets",
                                   `selected-text-format` = "static",
                                   title = "Select Income Buckets")
        ),
        pickerInput(inputId = "expense_buckets_filter_choices",
                    label = NULL,
                    selected = unlist(expenses_named_list, use.names = FALSE),#levels(monthly %>% filter(bucket_group != "Income") %>% pull(category) %>% fct_drop()),
                    choices = expenses_named_list,#levels(monthly %>% filter(bucket_group != "Income") %>% pull(category) %>% fct_drop()),
                    multiple = TRUE,
                    width = "fit",
                    options = list(`actions-box` = TRUE,
                                   header = "Expense Buckets",
                                   `selected-text-format` = "static",
                                   title = "Select Expense Buckets")
        ),
        p(strong("Income/Expense View"),
          style="margin-bottom: 5px;"),
        actionButton(inputId = "toggle_report_view", 
                     label = "Toggle: Buckets / Bucket Groups",
                     style="margin-bottom: 5px;"),
        actionButton(inputId = "toggle_zero_totals", 
                     label = "Toggle: Buckets With All Zeros",
                     style="margin-bottom: 5px;"),
        actionButton(inputId = "clear_selection", 
                     label = "Clear Selection",
                     style="margin-bottom: 5px;"),
        
        # Input controls for filtering accounts in net wealth report
        p(strong("Net Wealth View"),
          style="margin-bottom: 5px;"),
        actionButton(inputId = "select_all_accounts", 
                     label = "Show All Accounts",
                     style="margin-bottom: 5px;"),
        pickerInput(inputId = "netwealth_account_filter_choices",
                    label = NULL,
                    selected = unlist(accounts_named_list, use.names = FALSE),
                    choices = accounts_named_list,
                    multiple = TRUE,
                    width = "fit",
                    options = list(`actions-box` = TRUE,
                                   header = "Accounts",
                                   `selected-text-format` = "static",
                                   title = "Select Accounts")
        ),
        p(strong("Savings Rate View"),
          style="margin-bottom: 5px;"),
        actionButton(inputId = "select_config_saving_buckets", 
                     label = "Select Saving Buckets From \"config.R\"",
                     style="margin-bottom: 5px;"),
        pickerInput(inputId = "saving_buckets_filter_choices",
                    label = NULL,
                    selected = savings_buckets,
                    choices = expenses_named_list,
                    multiple = TRUE,
                    width = "fit",
                    options = list(`actions-box` = TRUE,
                                   header = "Saving Buckets",
                                   `selected-text-format` = "static",
                                   title = "Select Saving Buckets")
                    )
        ),
        # Use tabsets for the main panel to easily switch between reports
        mainPanel(width = 10, tabsetPanel(
            tabPanel("Income/Expense Report", DT::dataTableOutput("expenses_pr_month")),
            tabPanel("Transactions", 
                     p(strong("Filter the transactions by selecting cells in the Income/Expense Report."),
                       style = "margin: 5px"),
                     DT::dataTableOutput("transactions_table")),
            tabPanel("Sunburst Chart - Income",
                     p(strong("Click \"Other\" to see the buckets within that group and see \"config.R\" to change the threshold for \"Other\"."),
                       style="margin: 5px;"),
                     plotlyOutput("income_sunburstchart", height = height_income_piechart)),
            tabPanel("Sunburst Chart - Expenses",
                     p(strong("Click a bucket group to see the buckets within that group."),
                       style="margin: 5px;"),
                     plotlyOutput("expense_sunburstchart", height = height_expenses_sunburst)),
            tabPanel("Net Wealth",
                     p(strong("Hover to see amounts."),
                       style="margin: 5px;"),
                     plotlyOutput("net_wealth")),
            tabPanel("Savings Rate",
                     p(strong("Specify standard saving buckets in \"config.R\". Savings buckets are buckets used for transfers to off-budget saving accounts."),
                       style="margin: 5px;"),
                     DT::dataTableOutput("savings_rate_table")),
            tabPanel("Bucket Balances",
                     p(strong("Always shows the current balance in the Buckets. Not affected by filters."),
                       style="margin: 5px;"),
                     plotlyOutput("bucket_balances", height = height_bucket_balances)),
            tabPanel("Bucket Transactions",
                     p(strong("Select a bucket to show the plot."),
                       style="margin: 5px;"),
                     pickerInput(inputId = "bucket_transactions_selected",
                                 label = NULL,
                                 selected = NULL,
                                 choices = expenses_named_list,
                                 multiple = FALSE,
                                 width = "fit",
                                 options = list(`actions-box` = FALSE,
                                                header = "Bucket Transactions",
                                                title = "Select Bucket",
                                                `none-selected-text` = "Select Bucket",
                                                `live-search` = TRUE,
                                                `live-search-normalize` = TRUE)
                     ),
                     plotlyOutput("bucket_transactions", height = height_bucket_transactions)),
            tabPanel("Year Over Year",
                     p(strong("Select a bucket to show the plot."),
                       style="margin: 5px;"),
                     pickerInput(inputId = "year_over_year_selected",
                                 label = NULL,
                                 selected = NULL,
                                 choices = c(income_named_list, expenses_named_list),
                                 multiple = FALSE,
                                 width = "fit",
                                 options = list(`actions-box` = FALSE,
                                                header = "Year Over Year",
                                                title = "Select Bucket",
                                                `none-selected-text` = "Select Bucket",
                                                `live-search` = TRUE,
                                                `live-search-normalize` = TRUE)
                     ),
                     plotlyOutput("year_over_year", height = height_year_over_year))
            ))
        )
    )
)

    
